name: Cypress Tests

on:
  push:
    branches: ["master"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn run build
          start: yarn run preview
          wait-on: "http://localhost:3000"
          browser: chrome
          record: true
          group: "GitHub Actions"
